//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Univ.modeldb
{
    using System;
    using System.Collections.Generic;
    
    public partial class card_sa7ab
    {
        public int id { get; set; }
        public int id_card { get; set; }
        public double cost { get; set; }
        public double old_cost { get; set; }
        public string visa { get; set; }
    
        public virtual card card { get; set; }
    }
}
