//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Univ.modeldb
{
    using System;
    using System.Collections.Generic;
    
    public partial class card_sa7ab
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public card_sa7ab()
        {
            this.p_sa7ab = new HashSet<p_sa7ab>();
        }
    
        public int id { get; set; }
        public int id_card { get; set; }
        public double cost { get; set; }
        public double old_cost { get; set; }
        public string visa { get; set; }
    
        public virtual card card { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<p_sa7ab> p_sa7ab { get; set; }
    }
}
