//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Univ.modeldb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class univdb : DbContext
    {
        public univdb()
            : base("name=univdb")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<card> cards { get; set; }
        public virtual DbSet<card_7isab> card_7isab { get; set; }
        public virtual DbSet<card_dafa3> card_dafa3 { get; set; }
        public virtual DbSet<card_kanoni> card_kanoni { get; set; }
        public virtual DbSet<card_mo7sabi> card_mo7sabi { get; set; }
        public virtual DbSet<card_sa7ab> card_sa7ab { get; set; }
        public virtual DbSet<client> clients { get; set; }
        public virtual DbSet<p_sa7ab> p_sa7ab { get; set; }
        public virtual DbSet<part> parts { get; set; }
        public virtual DbSet<process> processes { get; set; }
        public virtual DbSet<year> years { get; set; }
    }
}
