//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Univ.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class part
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public float Cost { get; set; }
        public int Id_Pro { get; set; }
    
        public virtual process process { get; set; }
    }
}
